const express=require('express');const path=require('path');const fs=require('fs');const crypto=require('crypto');
const app=express();const PORT=process.env.PORT||3000;const ROOT=__dirname;const STORE=path.join(ROOT,'data','store.json');
app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(ROOT,'public')));
const prices={Single:1546,King:2060,Double:2576,Family:4120};const breakfast={Single:1,King:2,Double:2,Family:4};
const rooms=[['101','Single'],['102','Single'],['103','Double'],['104','King'],['105','King'],['106','Double'],['107','Single'],['108','Single'],['201','Single'],['202','Single'],['203','Double'],['204','King'],['205','King'],['206','Single'],['207','Family'],['208','King'],['209','King'],['210','King'],['211','Single'],['212','Single'],['301','Single'],['302','Single'],['303','Double'],['304','King'],['305','King'],['306','Single'],['307','Family'],['308','King'],['309','King'],['310','King'],['311','Single'],['312','Single'],['401','Single'],['402','Single'],['403','Double'],['404','King'],['405','King'],['406','Single'],['407','Family'],['408','King'],['409','King'],['410','King'],['411','Single'],['412','Single'],['501','Single'],['502','Single'],['503','King'],['504','King'],['505','King'],['506','Single'],['507','Family']].map(([number,type])=>({number,type,floor:number[0]}));
const OUT=new Set(['302','507']);
function load(){try{return JSON.parse(fs.readFileSync(STORE,'utf8'))}catch{return {bookings:[],payments:[],users:[],auditLogs:[],roomOverrides:{}}}}
let db=load();function save(){const tmp=STORE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,STORE)}
function id(prefix){return `${prefix}-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`}
function hash(p,s=crypto.randomBytes(16).toString('hex')){return `${s}:${crypto.scryptSync(p,s,64).toString('hex')}`};function verify(p,h){const [s,x]=String(h).split(':');if(!s||!x)return false;return crypto.timingSafeEqual(Buffer.from(x,'hex'),crypto.scryptSync(p,s,64))}
const sessions=new Map();function token(){return crypto.randomBytes(32).toString('hex')}
function seedAdmin(){if(!db.users.some(u=>u.username===process.env.SUPER_ADMIN_USERNAME||u.username==='admin')){const username=process.env.SUPER_ADMIN_USERNAME||'admin';const password=process.env.SUPER_ADMIN_PASSWORD||'CHANGE-ME-NOW';db.users.push({id:id('USR'),username,role:'SUPER_ADMIN',passwordHash:hash(password),disabled:false,createdAt:new Date().toISOString()});save()}}
seedAdmin();
function auth(req,res,next){const t=(req.headers.authorization||'').replace(/^Bearer /,'')||req.headers['x-session-token'];const s=t&&sessions.get(t);if(!s)return res.status(401).json({error:'Authentication required'});const u=db.users.find(x=>x.id===s.userId);if(!u||u.disabled)return res.status(401).json({error:'Account disabled'});req.user=u;next()}
function role(...roles){return (req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'Permission denied'})}
function audit(user,action,details){db.auditLogs.unshift({id:id('AUD'),userId:user?.id||null,action,details,createdAt:new Date().toISOString()});db.auditLogs=db.auditLogs.slice(0,1000);save()}
function dateNights(a,b){const x=new Date(a+'T00:00:00Z'),y=new Date(b+'T00:00:00Z');return Math.ceil((y-x)/86400000)}
function roomState(r){return db.roomOverrides[r.number]|| (OUT.has(r.number)?'OUT_OF_SERVICE':'AVAILABLE')}
function activeBooking(b){return ['PENDING_PAYMENT','CONFIRMED','CHECKED_IN'].includes(b.status)}
function availableRooms(checkIn,checkOut,type){return rooms.filter(r=>roomState(r)==='AVAILABLE'&&(!type||r.type===type)&&!db.bookings.some(b=>activeBooking(b)&&b.roomNumber===r.number&&b.checkIn<checkOut&&b.checkOut>checkIn))}
function calculate(type,ci,co){if(!prices[type])throw Error('Invalid room type');const nights=dateNights(ci,co);if(!Number.isInteger(nights)||nights<1)throw Error('Invalid stay dates');return {nights,total:prices[type]*nights}}
app.get('/api/health',(q,s)=>s.json({ok:true,service:'Palm Palace Hotel',rooms:rooms.length}));
app.get('/api/rooms',(q,s)=>s.json({rooms:rooms.map(r=>({...r,state:roomState(r)})),prices,breakfast}));
app.get('/api/availability',(q,s)=>{try{const {checkIn,checkOut,type}=q.query;if(!checkIn||!checkOut)throw Error('checkIn and checkOut are required');calculate(type||'Single',checkIn,checkOut);const a=availableRooms(checkIn,checkOut,type);s.json({rooms:a,count:a.length})}catch(e){s.status(400).json({error:e.message})}});
function createBooking(body,source='ONLINE',actor=null){const {roomType,roomNumber,checkIn,checkOut,guest}=body;if(!roomType||!roomNumber||!checkIn||!checkOut||!guest?.fullName||!guest?.phone)throw Error('Required booking information is missing');const room=rooms.find(r=>r.number===roomNumber&&r.type===roomType);if(!room||roomState(room)!=='AVAILABLE')throw Error('Selected room is unavailable');const calc=calculate(roomType,checkIn,checkOut);if(db.bookings.some(b=>activeBooking(b)&&b.roomNumber===roomNumber&&b.checkIn<checkOut&&b.checkOut>checkIn))throw Object.assign(new Error('Room has just been booked. Please select another room.'),{status:409});const b={id:id('PPH'),status:source==='WALK_IN'?'CONFIRMED':'PENDING_PAYMENT',source,roomType,roomNumber,checkIn,checkOut,nights:calc.nights,total:calc.total,breakfast:breakfast[roomType],guest:{fullName:guest.fullName.trim(),phone:guest.phone.trim(),email:(guest.email||'').trim(),notes:guest.notes||''},createdAt:new Date().toISOString(),createdBy:actor?.id||null};db.bookings.unshift(b);if(source==='WALK_IN'){db.payments.unshift({id:id('PAY'),bookingId:b.id,method:'OFFLINE',status:'PENDING',amount:b.total,reference:'',createdAt:new Date().toISOString()})}save();audit(actor,source==='WALK_IN'?'CREATE_WALK_IN':'CREATE_ONLINE',{bookingId:b.id,roomNumber});return b}
app.post('/api/bookings',(q,s)=>{try{s.status(201).json({booking:createBooking(q.body)})}catch(e){s.status(e.status||400).json({error:e.message})}});
app.get('/api/bookings/:id',(q,s)=>{const b=db.bookings.find(x=>x.id===q.params.id);if(!b)return s.status(404).json({error:'Booking not found'});s.json({booking:b})});
app.post('/api/bookings/:id/payment-intent',async(q,s)=>{const b=db.bookings.find(x=>x.id===q.params.id);if(!b)return s.status(404).json({error:'Booking not found'});if(b.status!=='PENDING_PAYMENT')return s.status(409).json({error:'Booking is not awaiting payment'});if(!process.env.PAYMENT_GATEWAY_URL)return s.status(503).json({error:'Payment gateway is not configured for this hotel yet.',bookingId:b.id,amount:b.total});
try{const r=await fetch(process.env.PAYMENT_GATEWAY_URL,{method:'POST',headers:{'content-type':'application/json',...(process.env.PAYMENT_GATEWAY_KEY?{authorization:`Bearer ${process.env.PAYMENT_GATEWAY_KEY}`}:{})},body:JSON.stringify({reference:b.id,amount:b.total,currency:'ETB',customer:b.guest})});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.message||'Gateway rejected payment request');s.json({bookingId:b.id,amount:b.total,paymentUrl:data.paymentUrl||data.checkoutUrl||data.url,status:'REDIRECT'})}catch(e){s.status(502).json({error:'Payment gateway request failed',detail:e.message})}});
app.post('/api/payments/webhook',(q,s)=>{const secret=process.env.PAYMENT_WEBHOOK_SECRET;if(secret){const sig=q.headers['x-webhook-secret'];if(sig!==secret)return s.status(401).json({error:'Invalid webhook signature'})}const {bookingId,reference,status,amount,transactionId}=q.body;const b=db.bookings.find(x=>x.id===bookingId||x.id===reference);if(!b)return s.status(404).json({error:'Booking not found'});if(status!=='PAID')return s.json({ok:true});if(Number(amount)!==Number(b.total))return s.status(400).json({error:'Amount mismatch'});if(b.status==='CONFIRMED')return s.json({ok:true,idempotent:true});b.status='CONFIRMED';db.payments.unshift({id:id('PAY'),bookingId:b.id,method:'GATEWAY',status:'PAID',amount:b.total,reference:transactionId||reference||b.id,createdAt:new Date().toISOString()});save();s.json({ok:true})});
app.post('/api/admin/login',(q,s)=>{const {username,password}=q.body||{};const u=db.users.find(x=>x.username===username&&!x.disabled);if(!u||!verify(password||'',u.passwordHash))return s.status(401).json({error:'Invalid username or password'});const t=token();sessions.set(t,{userId:u.id,createdAt:Date.now()});s.json({token:t,user:{id:u.id,username:u.username,role:u.role}})});
app.post('/api/admin/logout',auth,(q,s)=>{const t=(q.headers.authorization||'').replace(/^Bearer /,'');sessions.delete(t);s.json({ok:true})});app.get('/api/admin/me',auth,(q,s)=>s.json({user:{id:q.user.id,username:q.user.username,role:q.user.role}}));
app.get('/api/admin/dashboard',auth,role('SUPER_ADMIN','RECEPTION','FINANCE'),(q,s)=>{const today=new Date().toISOString().slice(0,10);const confirmed=db.bookings.filter(b=>['CONFIRMED','CHECKED_IN','CHECKED_OUT'].includes(b.status));s.json({rooms:rooms.length,available:rooms.filter(r=>roomState(r)==='AVAILABLE').length,outOfService:rooms.filter(r=>roomState(r)!=='AVAILABLE').length,todayBookings:db.bookings.filter(b=>b.createdAt.startsWith(today)).length,confirmed:confirmed.length,revenue:db.payments.filter(p=>p.status==='PAID').reduce((a,p)=>a+p.amount,0),pending:db.bookings.filter(b=>b.status==='PENDING_PAYMENT').length})});
app.get('/api/admin/bookings',auth,role('SUPER_ADMIN','RECEPTION','FINANCE'),(q,s)=>{let arr=db.bookings;if(q.query.status)arr=arr.filter(b=>b.status===q.query.status);s.json({bookings:arr.slice(0,500)})});
app.post('/api/admin/bookings/walk-in',auth,role('SUPER_ADMIN','RECEPTION'),(q,s)=>{try{s.status(201).json({booking:createBooking(q.body,'WALK_IN',q.user)})}catch(e){s.status(e.status||400).json({error:e.message})}});
app.post('/api/admin/bookings/:id/status',auth,role('SUPER_ADMIN','RECEPTION'),(q,s)=>{const b=db.bookings.find(x=>x.id===q.params.id);if(!b)return s.status(404).json({error:'Booking not found'});const allowed=['CONFIRMED','CHECKED_IN','CHECKED_OUT','CANCELLED','NO_SHOW'];if(!allowed.includes(q.body.status))return s.status(400).json({error:'Invalid status'});b.status=q.body.status;save();audit(q.user,'UPDATE_BOOKING_STATUS',{bookingId:b.id,status:b.status});s.json({booking:b})});
app.get('/api/admin/payments',auth,role('SUPER_ADMIN','FINANCE'),(q,s)=>s.json({payments:db.payments.slice(0,1000)}));
app.post('/api/admin/rooms/:number/state',auth,role('SUPER_ADMIN'),(q,s)=>{const r=rooms.find(x=>x.number===q.params.number);if(!r)return s.status(404).json({error:'Room not found'});const state=q.body.state;if(!['AVAILABLE','OUT_OF_SERVICE','MAINTENANCE'].includes(state))return s.status(400).json({error:'Invalid room state'});if(state==='AVAILABLE'){delete db.roomOverrides[r.number]}else db.roomOverrides[r.number]=state;save();audit(q.user,'ROOM_STATE_CHANGE',{roomNumber:r.number,state});s.json({room:{...r,state:roomState(r)}})});
app.get('/api/admin/users',auth,role('SUPER_ADMIN'),(q,s)=>s.json({users:db.users.map(u=>({id:u.id,username:u.username,role:u.role,disabled:u.disabled,createdAt:u.createdAt}))}));
app.post('/api/admin/users',auth,role('SUPER_ADMIN'),(q,s)=>{const {username,password,role:r}=q.body||{};if(!username||!password||!['SUPER_ADMIN','RECEPTION','FINANCE'].includes(r))return s.status(400).json({error:'username, password and valid role required'});if(db.users.some(u=>u.username===username))return s.status(409).json({error:'Username already exists'});const u={id:id('USR'),username,role:r,passwordHash:hash(password),disabled:false,createdAt:new Date().toISOString()};db.users.push(u);save();audit(q.user,'CREATE_USER',{username,role:r});s.status(201).json({user:{id:u.id,username:u.username,role:u.role,disabled:false}})});
app.post('/api/admin/users/:id/disable',auth,role('SUPER_ADMIN'),(q,s)=>{const u=db.users.find(x=>x.id===q.params.id);if(!u)return s.status(404).json({error:'User not found'});if(u.id===q.user.id)return s.status(400).json({error:'You cannot disable your own account'});u.disabled=true;save();audit(q.user,'DISABLE_USER',{userId:u.id});s.json({ok:true})});
app.get('/api/admin/audit',auth,role('SUPER_ADMIN'),(q,s)=>s.json({auditLogs:db.auditLogs.slice(0,500)}));
app.use((req,res)=>{if(req.method==='GET'&&!req.path.startsWith('/api/'))return res.sendFile(path.join(ROOT,'public','index.html'));res.status(404).json({error:'Not found'})});
app.listen(PORT,()=>console.log(`Palm Palace Hotel: http://localhost:${PORT}`));
